version: 2.1
jobs: 
  build: 
    docker:  
      - image: circleci/python:3.7 # ジョブのコマンドが実行されるプライマリ コンテナ
    steps: 
      - run: echo "hello world" # `echo` コマンドを実行します
      - run: pip install nkf
      - run: nkf --guess test.txt
