version: 2.1
jobs: 
  build: 
    docker:  
      - image: circleci/python:3.7 # ジョブのコマンドが実行されるプライマリ コンテナ
    steps: 
      - checkout
      - run: echo "hello world" # `echo` コマンドを実行します
      - run: sudo apt-get install nkf
      - run: find . -name "*.sql" | xargs nkf --guess | grep (LF) 
