version: 2.1

orbs:
  slack: circleci/slack@4.1.1

jobs: 
  build: 
    docker:  
      - image: circleci/python:3.7 
    steps: 
      - slack/notify:
          event: always
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "aaaaa a text notification*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master

