version: 2.1
jobs: 
  build: 
    docker:  
      - image: circleci/python:3.7 
    steps: 
      - checkout
      - run:
        name: 'NewLine Type Check'
        command: |
          sudo apt-get install nkf #nkfモジュールをインストール
          bash .circleci/newline_check.sh -e sql -i LF -d 各種モジュール/ETLModule/ELT_Framework/conf/ELT/ 

