version: 2.1
jobs: 
  build: 
    docker:  
      - image: circleci/python:3.7 
    steps: 
      - checkout
      - run:
          name: 'install module'
          command: sudo apt-get install nkf #nkfモジュールをインストール
      - run:
          name: 'check new line'
          command: bash .circleci/newline_check.sh -e txt -i LF

